# Generated by Django 4.2.11 on 2024-05-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181121_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='Resumes/')),
                ('portfolio', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('relocate', models.CharField(max_length=100)),
                ('worked_for', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
