# Generated by Django 4.2.11 on 2024-05-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_forms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='forms',
            new_name='FForms',
        ),
    ]
